<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * FEEDBACKS TABLE
     * Actionable improvement suggestions generated by AI.
     * Each feedback is a specific, prioritized recommendation.
     *
     * priority: critical (must fix) → high → medium → low (nice to have)
     * category: which section or aspect this feedback targets
     */
    public function up(): void
    {
        Schema::create('feedback_items', function (Blueprint $table) {
            $table->id();
            $table->foreignId('resume_id')->constrained()->cascadeOnDelete();

            $table->enum('priority', ['critical', 'high', 'medium', 'low'])->default('medium');
            $table->enum('category', [
                'contact',       // Missing phone/email/LinkedIn
                'summary',       // Weak or missing professional summary
                'keywords',      // ATS keyword optimization
                'experience',    // Work history issues
                'education',     // Education section problems
                'skills',        // Skills section improvements
                'format',        // Layout/formatting problems
                'content',       // Writing quality, action verbs
                'length',        // Too long or too short
                'ats',           // General ATS compatibility
                'achievements',  // Lack of quantified results
                'spelling',      // Grammar/spelling issues
                'other'
            ])->default('other');

            $table->string('title');                         // Short label: "Add LinkedIn URL"
            $table->text('description');                     // Detailed explanation
            $table->text('suggestion');                      // Exact actionable fix
            $table->text('example')->nullable();             // Before/after example

            $table->boolean('is_addressed')->default(false); // User marked as done
            $table->timestamp('addressed_at')->nullable();

            $table->timestamps();

            $table->index(['resume_id', 'priority']);
            $table->index('category');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('feedback_items');
    }
};
